### ISSUE TITLE
Help in one problem

### ISSUE THREAD

**Issue by mr-easy** [xphoniex/Google-Foobar#3]
I am currently trying to solve "Bringing a gun to a guard fight" level 4 problem. Can you please provide an explanation of the problem? I don't want a solution. I cannot understand the sample test given. I cannot get that output because I think I misunderstood the problem. Thanks for the help?(If you do :)

**Comment by xphoniex** [comment]
Here's the room with dimensions [3, 2] mentioned in the description: 
![map](https://user-images.githubusercontent.com/14107758/27404194-6465055a-56e2-11e7-9a8c-bf510f6dd8ce.jpg)
I've drawn the first 2 out of 7 vectors on it. If you don't know what a math vector is, google it.

[1,0] is very simple, go one step to right, zero step up.
[1,2] is one step right, two steps up. But as you can see it bounces down and hits the target.

**Comment by mr-easy** [comment]
Thank you very much!
I was thinking it in a wrong way, instead of positioning the characters (Commander and the guard) on the integer points, I was placing them inside the cells of the grid.
something like this:-
```
  __1____2___3__
1| C  | G  |    | 
 |____|____|____|
2|    |    |    | 
 |____|____|____|    
```
C = Commander
G = Guard

Sorry for the bad drawing   :P 

THANK YOU.
