### ISSUE TITLE
Help in running with bunnies

### ISSUE THREAD

**Issue by ankit451** [xphoniex/Google-Foobar#6]
first I check negative cycle then apply Johnson algorithm make  positive edge to positive and recursively check the node(and maintain its state in map ) for visiting 
case 1 node is not visited then visit and
case 2 if visited and  its state is less than of previous  then also go to that place
if I apply case1 only  7/10 test case passes and apply case1 and case 2 time timed exceed 
I know case1 is not enough and case1  and case 2 passes sample test case 
Help where I miss the logic

**Comment by xphoniex** [comment]
Why you are using Johnson here?

If there's a negative cycle, you can save all the bunnies, so you don't need to waste time checking "case 2"

**Comment by ankit451** [comment]
yes, I check first is there any negative cycle, then apply Johnson algorithm I got the same result as above without Johnson also. I apply Johnson just for making positive edge but there is no use.
as in sample case node 4 is visited again, that's why I applied to case 2

**Comment by ankit451** [comment]
ohh i got the error in my code,Now it works 
Thank you for your time
