### ISSUE TITLE
Running with bunnies?

### ISSUE THREAD

**Issue by kushalm9203** [xphoniex/Google-Foobar#7]
Hey! Were you able to pass all the test cases for Running with bunnies? I didn't use your code but I see that what i have done is essentially the same. I'm not able to pass one of the test cases (Test 10).

**Comment by xphoniex** [comment]
Hey! Yes I was. Maybe use my code just to see if still passes and then see what you might be doing wrong?

**Comment by sibashisch** [comment]
@kushalm9203 I had the same problem and it was solved by reading the problem statement carefully. Are you doing exactly what is asked when you have multiple lists of same size?
